### ISSUE TITLE
Is this extension still maintained?

### ISSUE THREAD

**Issue by dafttt** [myflyingbox/magento-extension#7]
Hello,

@tbelliard ?

Thanks.

**Comment by tbelliard** [comment]
Hi!
It hasn't been updated in a while because very few of our customers are using Magento (we have many more WooCommerce and Prestashop users).
This extension also requires extensive knowledge of the Magento platform, which we do not have internally, hence the low frequency of updates.
It is not abandoned, however. If you are interested in our services and would need this extension for a version of Magento not currently supported, please let us know at info@myflyingbox.com so we can evaluate our course of action.

**Comment by dafttt** [comment]
Thanks for this informations.
